import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/patterns/navbar";
import Footer from "@/patterns/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mauro Santos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
